keys:
  - &admin_bytesudoer age1l7gqrfhgjf0n6q0tp2mx4jc8w6zanvfnh8742wqczu83249lc9ds3ew42k
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    age: *admin_bytesudoer
