# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{


  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];


  networking.useDHCP = lib.mkDefault true;

  # powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  #Enable Nested virtualization
  boot.extraModprobeConfig = "options kvm_intel nested=1";
}
